name: "melos_monorepo"
publish_to: none

# This allows us to use melos on itself during development.
executables:
  melos: melos_dev

dev_dependencies:
  melos:
    path: ./packages/melos
  path: ^1.7.0
  yaml: ^3.1.0

# These allow us to use melos on itself during development.
# If you make a new local package in this repo that the melos package
# will depend on, then make sure to add it here otherwise you'll face
# "'pubspec.yaml' has been modified since".. issues.
dependency_overrides:
  conventional_commit:
    path: ./packages/conventional_commit
  melos:
    path: ./packages/melos

environment:
  sdk: ">=2.2.2 <3.0.0"
