name: melos_workspace

environment:
  sdk: ">=2.18.0 <3.0.0"

# This allows us to use melos on itself during development.
executables:
  melos: melos_dev

dev_dependencies:
  melos:
    path: packages/melos
  path: ^1.7.0
  yaml: ^3.1.0
