name: melos
description:
  A tool for managing Dart & Flutter repositories with multiple packages
  (monorepo). Supports automated versioning via Conventional Commits. Inspired
  by JavaScripts Lerna package.
version: 3.4.0
homepage: https://melos.invertase.dev/~melos-latest
repository: https://github.com/invertase/melos/tree/main/packages/melos
issue_tracker: https://github.com/invertase/melos/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

executables:
  melos:

dependencies:
  ansi_styles: ^0.3.1
  args: ^2.0.0
  cli_launcher: ^0.3.0
  cli_util: '>=0.3.0 <0.5.0'
  collection: ^1.14.12
  conventional_commit: ^0.6.0+1
  file: ^7.0.0
  glob: ^2.1.0
  graphs: ^2.1.0
  http: ">=0.13.1 <2.0.0"
  meta: ^1.1.8
  mustache_template: ^2.0.0
  path: ^1.7.0
  platform: ^3.1.0
  pool: ^1.4.0
  prompts: ^2.0.0
  pub_semver: ^2.0.0
  pub_updater: ^0.4.0
  pubspec: ^2.1.0
  string_scanner: ^1.0.5
  yaml: ^3.1.0
  yaml_edit: ^2.0.2

dev_dependencies:
  mockito: ^5.1.0
  test: ^1.17.5
