name: melos
description: "A tool for managing Dart & Flutter repositories with multiple packages (monorepo). Supports automated versioning via Conventional Commits. Inspired by JavaScripts Lerna package."
version: 1.3.0
homepage: "https://github.com/invertase/melos"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansi_styles: ^0.3.1
  args: ^2.0.0
  # peer-dependencies of the local `prompts` fork. To remove once prompts null-safety is published
  charcode: ^1.0.0
  cli_util: ^0.3.0
  collection: ^1.14.12
  conventional_commit: ^0.4.2
  file: ^6.1.0
  glob: ^2.0.1
  graphs: ^2.1.0
  http: ^0.13.1
  # peer-dependencies of the local `prompts` fork. To remove once prompts null-safety is published
  io: ^1.0.0
  meta: ^1.1.8
  mustache_template: ^2.0.0
  path: ^1.7.0
  platform: ^3.1.0
  pool: ^1.4.0
  pub_semver: ^2.0.0
  pubspec: ^2.1.0
  string_scanner: ^1.0.5
  yaml: ^3.1.0

dev_dependencies:
  nock: ^1.2.0
  test: ^1.17.5

executables:
  melos:
