name: "melos"
description: "A tool for managing Dart projects with multiple packages. Inspired by JavaScripts Lerna package."
version: "0.3.11"
homepage: "https://github.com/invertase/melos"
executables:
  melos:
dependencies:
  ansi_styles: ^0.1.1+1
  conventional_commit: ^0.1.0+2
  args: ^1.6.0
  http: ^0.12.2
  pool: ^1.4.0
  collection: ^1.14.12
  string_scanner: ^1.0.5
  cli_util: ^0.2.0
  glob: ^1.2.0
  path: ^1.7.0
  yaml: ^2.2.1
  meta: ^1.1.8
  prompts: ^1.3.1
  yamlicious: ^0.1.0
  pub_semver: ^1.4.4
dev_dependencies:
  pedantic: ^1.9.0

environment:
  sdk: ">=2.2.2 <3.0.0"
