name: melos
description:
  A tool for managing Dart & Flutter repositories with multiple packages
  (monorepo). Supports automated versioning via Conventional Commits. Inspired
  by JavaScripts Lerna package.
version: 6.1.0
homepage: https://melos.invertase.dev/~melos-latest
repository: https://github.com/invertase/melos/tree/main/packages/melos
issue_tracker: https://github.com/invertase/melos/issues

topics:
  - tool
  - repository-management
  - cli
  - monorepo
  - lerna

environment:
  sdk: ">=3.1.0 <4.0.0"

executables:
  melos:

dependencies:
  ansi_styles: ^0.3.2+1
  args: ^2.5.0
  async: ^2.11.0
  cli_launcher: ^0.3.1
  cli_util: ^0.4.1
  collection: ^1.18.0
  conventional_commit: ^0.6.0+1
  file: ^7.0.0
  glob: ^2.1.2
  graphs: ^2.3.2
  http: ^1.2.2
  intl: ^0.19.0
  meta: ^1.16.0
  mustache_template: ^2.0.0
  path: ^1.9.0
  platform: ^3.1.5
  pool: ^1.5.1
  prompts: ^2.0.0
  pub_semver: ^2.1.4
  pub_updater: ^0.4.0
  pubspec: ^2.3.0
  string_scanner: ^1.2.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1

dev_dependencies:
  mockito: ^5.4.4
  test: ^1.25.8
