name: melos
description: "A tool for managing Dart & Flutter repositories with multiple packages (monorepo). Supports automated versioning via Conventional Commits. Inspired by JavaScripts Lerna package."
version: 0.4.9
homepage: "https://github.com/invertase/melos"
executables:
  melos:
dependencies:
  ansi_styles: ^0.2.0
  args: ^1.6.0
  cli_util: ^0.2.0
  collection: ^1.14.12
  conventional_commit: ^0.3.0+1
  glob: ^1.2.0
  http: ^0.12.2
  meta: ^1.1.8
  mustache_template: ^2.0.0
  path: ^1.7.0
  pool: ^1.4.0
  prompts: ^1.3.1
  pub_semver: ^1.4.4
  string_scanner: ^1.0.5
  yaml: ^2.2.1
  yamlicious: ^0.1.0
dev_dependencies:
  test: any
environment:
  sdk: ">=2.2.2 <3.0.0"
